--- Imported ladder snapshot generated by PvPLedger collector.
PvPLedgerLadderData = PvPLedgerLadderData or {}
PvPLedgerLadderData.US = PvPLedgerLadderData.US or {}
PvPLedgerLadderData.US.arena3v3 = {
    snapshotId = "us-arena3v3-s42-2026-08-18",
    region = "US",
    bracket = "arena3v3",
    season = 42,
    snapshotDate = "2026-08-18",
    generatedAt = "2026-08-18T18:56:46Z",
    source = "blizzard-api+seramate",
    overall = {
        listedCount = 6,
        avgListedRating = 96,
        medianListedRating = 96.0,
        top100Avg = 96,
        cutoffs = {
        },
        buckets = {
            ["0-99"] = 6,
        },
        ratedPopulation = 0,
        titleCutoffs = {
        },
    },
    byClass = {
        ["DEMONHUNTER"] = {
            listedCount = 1,
            avgListedRating = 96,
            medianListedRating = 96,
            top100Avg = 96,
            highest = 96,
            buckets = {
                ["0-99"] = 1,
            },
        },
    },
    bySpec = {
        ["DEMONHUNTER_HAVOC"] = {
            listedCount = 1,
            avgListedRating = 96,
            medianListedRating = 96,
            top100Avg = 96,
            highest = 96,
            buckets = {
                ["0-99"] = 1,
            },
        },
    },
    players = {
        ["bludechami-ragnaros"] = {
            displayName = "Bludechami-ragnaros",
            specKey = "",
            rating = 96,
            rank = 1,
            wins = 1,
            losses = 0,
            faction = "ALLIANCE",
        },
        ["depose-bleedinghollow"] = {
            displayName = "Depose-bleeding-hollow",
            specKey = "",
            rating = 96,
            rank = 1,
            wins = 1,
            losses = 0,
            faction = "ALLIANCE",
        },
        ["edger-bleedinghollow"] = {
            displayName = "Edger-bleeding-hollow",
            specKey = "",
            rating = 96,
            rank = 1,
            wins = 1,
            losses = 0,
            faction = "ALLIANCE",
        },
        ["hardtekk-illidan"] = {
            displayName = "Hardtekk-illidan",
            specKey = "DEMONHUNTER_HAVOC",
            rating = 96,
            rank = 1,
            wins = 1,
            losses = 0,
            faction = "ALLIANCE",
        },
        ["iïlpümpx-tichondrius"] = {
            displayName = "Iïlpümpx-tichondrius",
            specKey = "",
            rating = 96,
            rank = 1,
            wins = 1,
            losses = 0,
            faction = "ALLIANCE",
        },
        ["ragebaitx-bleedinghollow"] = {
            displayName = "Ragebaitx-bleeding-hollow",
            specKey = "",
            rating = 96,
            rank = 1,
            wins = 1,
            losses = 0,
            faction = "ALLIANCE",
        },
    },
}
