"""Render ExportAck.lua for the PvPLedger AppHelper bridge addon."""

from __future__ import annotations

from pathlib import Path


def _lua_string(value: str) -> str:
    """Escape one string for inclusion in generated Lua source."""

    escaped = value.replace("\\", "\\\\").replace('"', '\\"')
    return f'"{escaped}"'


def render_export_ack_lua(*, uploaded_match_ids: list[str], batch_id: str, uploaded_at: str) -> str:
    """
    Build ExportAck.lua contents for one successful upload batch.

    Parameters
    ----------
    uploaded_match_ids:
        Match IDs acknowledged by the upload destination.
    batch_id:
        Unique batch identifier used for deduplication in-game.
    uploaded_at:
        UTC timestamp string for the upload event.

    Returns
    -------
    str
        Complete ExportAck.lua file contents.
    """

    lines = [
        "--- Generated by PvPLedger Sync. Do not edit manually.",
        "PVL_AppHelperExportAck = {",
        f"    batchId = {_lua_string(batch_id)},",
        f"    uploadedAt = {_lua_string(uploaded_at)},",
        "    uploadedMatchIds = {",
    ]

    for match_id in uploaded_match_ids:
        lines.append(f"        {_lua_string(str(match_id))},")

    lines.extend([
        "    },",
        "}",
        "",
    ])
    return "\n".join(lines)


def write_export_ack(
    *,
    destination: Path,
    uploaded_match_ids: list[str],
    batch_id: str,
    uploaded_at: str,
) -> Path:
    """
    Write ExportAck.lua into the AppHelper addon folder.

    Parameters
    ----------
    destination:
        Target path, typically `PvPLedger-AppHelper/ExportAck.lua`.
    uploaded_match_ids:
        Match IDs to acknowledge to the in-game export queue.
    batch_id:
        Unique batch identifier.
    uploaded_at:
        UTC timestamp string.

    Returns
    -------
    Path
        Path to the written file.
    """

    destination.parent.mkdir(parents=True, exist_ok=True)
    destination.write_text(
        render_export_ack_lua(
            uploaded_match_ids=uploaded_match_ids,
            batch_id=batch_id,
            uploaded_at=uploaded_at,
        ),
        encoding="utf-8",
    )
    return destination


def clear_export_ack(destination: Path) -> Path:
    """
    Reset ExportAck.lua to an empty acknowledgement state.

    Parameters
    ----------
    destination:
        Target ExportAck.lua path.

    Returns
    -------
    Path
        Path to the written file.
    """

    destination.write_text(
        "\n".join([
            "--- Match upload acknowledgements from PvPLedger Sync.",
            "--- Regenerated by the desktop app after successful export upload.",
            "PVL_AppHelperExportAck = nil",
            "",
        ]),
        encoding="utf-8",
    )
    return destination
