#!/usr/bin/env python3
"""Render PvPLedger-AppHelper/AppData.lua from packaged ladder snapshot files."""

from __future__ import annotations

import re
from datetime import datetime, timezone
from pathlib import Path

BRACKET_PATTERN = re.compile(r"PvPLedgerLadderData\.(\w+)\s*=\s*\{")


def extract_snapshot_table(text: str, bracket_key: str) -> str | None:
    """Extract one snapshot table literal from a packaged ladder Lua file."""

    marker = f"PvPLedgerLadderData.{bracket_key} = {{"
    start = text.find(marker)
    if start < 0:
        return None

    brace_start = text.find("{", start)
    if brace_start < 0:
        return None

    depth = 0
    for index in range(brace_start, len(text)):
        char = text[index]
        if char == "{":
            depth += 1
        elif char == "}":
            depth -= 1
            if depth == 0:
                return text[brace_start : index + 1]
    return None


def render_app_data_lua(*, data_dir: Path, region: str) -> str:
    """Build AppData.lua content from existing LadderData snapshot files."""

    snapshots: list[tuple[str, str]] = []
    for path in sorted(data_dir.glob(f"LadderData_{region.upper()}_*.lua")):
        text = path.read_text(encoding="utf-8")
        bracket_match = re.search(r'bracket = "([^"]+)"', text)
        if not bracket_match:
            continue

        bracket = bracket_match.group(1)
        table_literal = extract_snapshot_table(text, bracket)
        if not table_literal:
            continue

        snapshots.append((bracket, table_literal))

    generated_at = datetime.now(timezone.utc).strftime("%Y-%m-%dT%H:%M:%SZ")
    lines = [
        "--- App data bridge for PvPLedger Sync.",
        "--- This file is regenerated by Collector/fetch_all.py and the PvPLedger Sync desktop app.",
        "--- DO NOT EDIT MANUALLY.",
        "PVL_AppHelperPendingSnapshots = PVL_AppHelperPendingSnapshots or {}",
        "PVL_AppHelperSyncInfo = {",
        f'    lastSync = {int(datetime.now(timezone.utc).timestamp())},',
        f'    generatedAt = "{generated_at}",',
        f'    region = "{region.upper()}",',
        '    source = "collector",',
        "}",
        "",
    ]

    for bracket, table_literal in snapshots:
        lines.extend([
            f"PVL_AppHelperPendingSnapshots.{bracket} = {table_literal}",
            "",
        ])

    return "\n".join(lines)


def write_app_helper_app_data(*, data_dir: Path, region: str, addon_dir: Path) -> Path:
    """Write AppData.lua into the PvPLedger-AppHelper addon folder."""

    addon_dir.mkdir(parents=True, exist_ok=True)
    output = addon_dir / "AppData.lua"
    output.write_text(render_app_data_lua(data_dir=data_dir, region=region), encoding="utf-8")
    return output


def main() -> None:
    """Render AppData.lua from existing Data/LadderData_*.lua files."""

    repo_root = Path(__file__).resolve().parent.parent
    data_dir = repo_root / "Data"
    addon_dir = repo_root / "PvPLedger-AppHelper"
    output = write_app_helper_app_data(data_dir=data_dir, region="US", addon_dir=addon_dir)
    print(f"Wrote {output}")


if __name__ == "__main__":
    main()
