"""Render PvPLedger-AppHelper/AppData.lua from packaged ladder snapshot files."""

from __future__ import annotations

import re
from datetime import datetime, timezone
from pathlib import Path

NESTED_BRACKET_PATTERN = re.compile(r"PvPLedgerLadderData\.([A-Z]+)\.(\w+)\s*=\s*\{")
LEGACY_BRACKET_PATTERN = re.compile(r"PvPLedgerLadderData\.(\w+)\s*=\s*\{")


def extract_braced_literal(text: str, marker: str) -> str | None:
    """Extract one Lua table literal that starts at ``marker``."""

    start = text.find(marker)
    if start < 0:
        return None

    brace_start = text.find("{", start)
    if brace_start < 0:
        return None

    depth = 0
    for index in range(brace_start, len(text)):
        char = text[index]
        if char == "{":
            depth += 1
        elif char == "}":
            depth -= 1
            if depth == 0:
                return text[brace_start : index + 1]
    return None


def extract_snapshot_table(text: str, bracket_key: str, region: str) -> str | None:
    """Extract one snapshot table literal from a packaged ladder Lua file."""

    region_upper = region.upper()
    nested_marker = f"PvPLedgerLadderData.{region_upper}.{bracket_key} = {{"
    nested = extract_braced_literal(text, nested_marker)
    if nested:
        return nested

    legacy_marker = f"PvPLedgerLadderData.{bracket_key} = {{"
    legacy = extract_braced_literal(text, legacy_marker)
    if not legacy:
        return None

    region_match = re.search(r'region = "([^"]+)"', legacy)
    if region_match and region_match.group(1).upper() != region_upper:
        return None

    return legacy


def regional_manifest_filename(region: str) -> str:
    """Return the ladder manifest filename for one region."""

    region_upper = region.upper()
    if region_upper == "US":
        return "ladder-manifest.json"
    return f"ladder-manifest-{region_upper}.json"


def regional_app_data_filename(region: str) -> str:
    """Return the AppHelper bridge filename for one region."""

    region_upper = region.upper()
    if region_upper == "US":
        return "AppData.lua"
    return f"AppData-{region_upper}.lua"


def render_app_data_lua(*, data_dir: Path, region: str) -> str:
    """Build AppData.lua content from existing LadderData snapshot files."""

    snapshots: list[tuple[str, str]] = []
    for path in sorted(data_dir.glob(f"LadderData_{region.upper()}_*.lua")):
        text = path.read_text(encoding="utf-8")
        bracket_match = re.search(r'bracket = "([^"]+)"', text)
        if not bracket_match:
            continue

        bracket = bracket_match.group(1)
        table_literal = extract_snapshot_table(text, bracket, region)
        if not table_literal:
            continue

        snapshots.append((bracket, table_literal))

    generated_at = datetime.now(timezone.utc).strftime("%Y-%m-%dT%H:%M:%SZ")
    region_upper = region.upper()
    sync_info_lines = [
        f'    lastSync = {int(datetime.now(timezone.utc).timestamp())},',
        f'    generatedAt = "{generated_at}",',
        f'    region = "{region_upper}",',
        '    source = "collector",',
    ]

    if region_upper == "US":
        lines = [
            "--- App data bridge for PvPLedger Sync.",
            "--- This file is regenerated by Collector/fetch_all.py and the PvPLedger Sync desktop app.",
            "--- DO NOT EDIT MANUALLY.",
            "PVL_AppHelperPendingSnapshots = PVL_AppHelperPendingSnapshots or {}",
            "PVL_AppHelperSyncInfo = {",
            *sync_info_lines,
            "}",
            "",
        ]
        snapshot_prefix = "PVL_AppHelperPendingSnapshots"
    else:
        lines = [
            "--- App data bridge for PvPLedger Sync.",
            "--- This file is regenerated by Collector/fetch_all.py and the PvPLedger Sync desktop app.",
            "--- DO NOT EDIT MANUALLY.",
            "PVL_AppHelperPendingSnapshotsByRegion = PVL_AppHelperPendingSnapshotsByRegion or {}",
            "PVL_AppHelperSyncInfoByRegion = PVL_AppHelperSyncInfoByRegion or {}",
            f"PVL_AppHelperPendingSnapshotsByRegion.{region_upper} = PVL_AppHelperPendingSnapshotsByRegion.{region_upper} or {{}}",
            f"PVL_AppHelperSyncInfoByRegion.{region_upper} = {{",
            *sync_info_lines,
            "}",
            "",
        ]
        snapshot_prefix = f"PVL_AppHelperPendingSnapshotsByRegion.{region_upper}"

    for bracket, table_literal in snapshots:
        lines.extend([
            f"{snapshot_prefix}.{bracket} = {table_literal}",
            "",
        ])

    return "\n".join(lines)


def write_app_helper_app_data(*, data_dir: Path, region: str, addon_dir: Path) -> Path:
    """Write the regional AppHelper bridge file into the PvPLedger-AppHelper addon folder."""

    addon_dir.mkdir(parents=True, exist_ok=True)
    output = addon_dir / regional_app_data_filename(region)
    output.write_text(render_app_data_lua(data_dir=data_dir, region=region), encoding="utf-8")
    return output


def main() -> None:
    """Render AppData.lua from existing Data/LadderData_*.lua files."""

    repo_root = Path(__file__).resolve().parent.parent
    data_dir = repo_root / "Data"
    addon_dir = repo_root / "PvPLedger-AppHelper"
    output = write_app_helper_app_data(data_dir=data_dir, region="US", addon_dir=addon_dir)
    print(f"Wrote {output}")


if __name__ == "__main__":
    main()
